apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka-qa
spec:
  ports:
  - port: 2181
    protocol: TCP
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka-qa
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      volumes:
      - name: zookeeper-data
        hostPath:
          path: /Users/vaibhavzodge/Documents/ALL_GIT_REPO/DnyanYog/sre/k8s-apps/kafka/zookeeper/vol_zookeeper_data
      containers:
      containers:
      - env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        image: docker.io/bitnami/zookeeper:3.8
        imagePullPolicy: Never
        name: zookeeper
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: zookeeper-data
          mountPath: /zookeeper-data
